#define INT_FAST16_MIN  INT16_MIN
#define INT_FAST32_MIN  INT32_MIN

#define INT_FAST16_MAX  INT16_MAX
#define INT_FAST32_MAX  INT32_MAX

#define UINT_FAST16_MAX UINT16_MAX
#define UINT_FAST32_MAX UINT32_MAX

#define INTPTR_MIN      INT16_MIN
#define INTPTR_MAX      INT16_MAX
#define UINTPTR_MAX     UINT16_MAX
#define PTRDIFF_MIN     INT16_MIN
#define PTRDIFF_MAX     INT16_MAX
#define SIZE_MAX        UINT16_MAX
